name: ML Run on Docker

# on mentions a trigger for the workflow
on:
  push:

jobs:
  ml_run:
    runs-on: ubuntu-latest

    container:
      image: jupyter/scipy-notebook:latest
      options: --user root

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      # - name: Set up Python
      #   uses: actions/setup-python@v6
      #   with:
      #     python-version: '3.13'

      - name: Install dependencies
        run: |
          python ml_example.py