name: ML Run in Sequence

# on mentions a trigger for the workflow
on:
  push:

jobs:
  ml_run:
    runs-on: ubuntu-latest


    container:
      image: jupyter/scipy-notebook:latest
      options: --user root

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Run ML example
        run: |
          python ml_example.py
  deploy:
    needs: ml_run
    runs-on: ubuntu-latest

    container:
      image: jupyter/scipy-notebook:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Run ML example 2
        run: |
          python ml_example_2.py
